# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: ['main']

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCE_INSTANCE: intorest-vm
  GCE_INSTANCE_ZONE: asia-northeast3

jobs:
  build:
    runs-on: ubuntu-latest
    
    env: 
      CI: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create SA KEY file
        run: |
          echo 'GCP_SA_KEY'
          echo '${{ secrets.GCP_SA_KEY }}'
          cat ./*.json >> ./server/src/main/resources/key.json

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        working-directory: server
        run: chmod +x gradlew
      - name: Build
        working-directory: server
        run: ./gradlew build -x test
      - name: Move jar to root
        run: mv ./server/build/libs/*.jar ./server.jar
        
      - name: Deploy gcp
        uses: appleboy/scp-action@master
        with: 
          host: '${{ secrets.SSH_HOST }}'
          username: '${{ secrets.SSH_USERNAME }}'
          key: '${{ secrets.SSH_KEY }}'
          source: "server.jar"
          target: "~"

      - name: Run Application
        uses: appleboy/ssh-action@master
        with: 
          host: '${{ secrets.SSH_HOST }}'
          username: '${{ secrets.SSH_USERNAME }}'
          key: '${{ secrets.SSH_KEY }}'
          script: sh run.sh


#       - id: 'auth'
#         name: 'Authenticate to Google Cloud'
#         uses: 'google-github-actions/auth@v1'
#         with:
#           credentials_json: '${{ secrets.GCP_SA_KEY }}'
#       - name: Set up Cloud SDK
#         uses: google-github-actions/setup-gcloud@v1

#       - name: 'Upload file'
#         run: |
#           touch test2.txt
#           gcloud compute scp --project='${{ secrets.GCP_PROJECT_ID }}' --zone='asia-northeast3-a' ./test2.txt 'instance-vm:~'

#       - name: 'Run Application'
#         uses: 'google-github-actions/ssh-compute@v0'
#         with:
#          instance_name: 'instance-vm'
#          zone: 'asia-northeast3-a'
#          ssh_keys_dir: '~/.ssh'
#          ssh_private_key: '${{ secrets.SSH_KEY }}'
#          command: 'java -jar -Dspring.profiles.active=gcs java.jar'









