# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        working-directory: server
        run: chmod +x gradlew
      - name: Build with Gradle
        working-directory: server
        run: ./gradlew build -x test
      - name: Move jar to root
        run: mv ./server/build/libs/*.jar ./server.jar
